// Code generated by mockery v2.23.2. DO NOT EDIT.

package service

import (
	domain "github.com/pklimuk-eng-thesis/control-station/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSensorService is an autogenerated mock type for the SensorService type
type MockSensorService struct {
	mock.Mock
}

type MockSensorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorService) EXPECT() *MockSensorService_Expecter {
	return &MockSensorService_Expecter{mock: &_m.Mock}
}

// GetInfo provides a mock function with given fields:
func (_m *MockSensorService) GetInfo() (domain.SensorInfo, error) {
	ret := _m.Called()

	var r0 domain.SensorInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.SensorInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.SensorInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.SensorInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorService_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type MockSensorService_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
func (_e *MockSensorService_Expecter) GetInfo() *MockSensorService_GetInfo_Call {
	return &MockSensorService_GetInfo_Call{Call: _e.mock.On("GetInfo")}
}

func (_c *MockSensorService_GetInfo_Call) Run(run func()) *MockSensorService_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSensorService_GetInfo_Call) Return(_a0 domain.SensorInfo, _a1 error) *MockSensorService_GetInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorService_GetInfo_Call) RunAndReturn(run func() (domain.SensorInfo, error)) *MockSensorService_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetSensorLogsFromDataServiceLimitN provides a mock function with given fields: limit
func (_m *MockSensorService) GetSensorLogsFromDataServiceLimitN(limit int) ([]domain.SensorData, error) {
	ret := _m.Called(limit)

	var r0 []domain.SensorData
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.SensorData, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.SensorData); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SensorData)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorService_GetSensorLogsFromDataServiceLimitN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSensorLogsFromDataServiceLimitN'
type MockSensorService_GetSensorLogsFromDataServiceLimitN_Call struct {
	*mock.Call
}

// GetSensorLogsFromDataServiceLimitN is a helper method to define mock.On call
//   - limit int
func (_e *MockSensorService_Expecter) GetSensorLogsFromDataServiceLimitN(limit interface{}) *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call {
	return &MockSensorService_GetSensorLogsFromDataServiceLimitN_Call{Call: _e.mock.On("GetSensorLogsFromDataServiceLimitN", limit)}
}

func (_c *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call) Run(run func(limit int)) *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call) Return(_a0 []domain.SensorData, _a1 error) *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call) RunAndReturn(run func(int) ([]domain.SensorData, error)) *MockSensorService_GetSensorLogsFromDataServiceLimitN_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleDetected provides a mock function with given fields:
func (_m *MockSensorService) ToggleDetected() (domain.SensorInfo, error) {
	ret := _m.Called()

	var r0 domain.SensorInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.SensorInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.SensorInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.SensorInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorService_ToggleDetected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleDetected'
type MockSensorService_ToggleDetected_Call struct {
	*mock.Call
}

// ToggleDetected is a helper method to define mock.On call
func (_e *MockSensorService_Expecter) ToggleDetected() *MockSensorService_ToggleDetected_Call {
	return &MockSensorService_ToggleDetected_Call{Call: _e.mock.On("ToggleDetected")}
}

func (_c *MockSensorService_ToggleDetected_Call) Run(run func()) *MockSensorService_ToggleDetected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSensorService_ToggleDetected_Call) Return(_a0 domain.SensorInfo, _a1 error) *MockSensorService_ToggleDetected_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorService_ToggleDetected_Call) RunAndReturn(run func() (domain.SensorInfo, error)) *MockSensorService_ToggleDetected_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleEnabled provides a mock function with given fields:
func (_m *MockSensorService) ToggleEnabled() (domain.SensorInfo, error) {
	ret := _m.Called()

	var r0 domain.SensorInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (domain.SensorInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() domain.SensorInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.SensorInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorService_ToggleEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleEnabled'
type MockSensorService_ToggleEnabled_Call struct {
	*mock.Call
}

// ToggleEnabled is a helper method to define mock.On call
func (_e *MockSensorService_Expecter) ToggleEnabled() *MockSensorService_ToggleEnabled_Call {
	return &MockSensorService_ToggleEnabled_Call{Call: _e.mock.On("ToggleEnabled")}
}

func (_c *MockSensorService_ToggleEnabled_Call) Run(run func()) *MockSensorService_ToggleEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSensorService_ToggleEnabled_Call) Return(_a0 domain.SensorInfo, _a1 error) *MockSensorService_ToggleEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorService_ToggleEnabled_Call) RunAndReturn(run func() (domain.SensorInfo, error)) *MockSensorService_ToggleEnabled_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockSensorService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSensorService creates a new instance of MockSensorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSensorService(t mockConstructorTestingTNewMockSensorService) *MockSensorService {
	mock := &MockSensorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
